import { invoke } from "@tauri-apps/api/core";
import { MEDIAPIPE_PACKAGE_VERSION } from "../../mediapipe/mediapipeProvenance";
import { MediaPipeTrackingSource } from "../../mediapipe/mediapipeTrackingSource";
import { M0E5EvidenceRunner } from "./m0e5EvidenceRunner";
import type { M0E5ProcedureStep } from "./m0e5Procedure";

export type M0E5InvalidationReason = "external-interruption" | "operator-moved-after-settling-during-stationary-capture";
const EXTERNAL_INTERRUPTION: M0E5InvalidationReason = "external-interruption";
const OPERATOR_MOVEMENT: M0E5InvalidationReason = "operator-moved-after-settling-during-stationary-capture";

export function allowedM0E5InvalidationReasons(step: M0E5ProcedureStep | undefined): readonly M0E5InvalidationReason[] {
  return step?.scenarioId === "neutral-stationary" && step.kind === "capture" ? [EXTERNAL_INTERRUPTION, OPERATOR_MOVEMENT] : [EXTERNAL_INTERRUPTION];
}

export function normalizeM0E5InvalidationReason(step: M0E5ProcedureStep | undefined, selected: M0E5InvalidationReason): M0E5InvalidationReason {
  return allowedM0E5InvalidationReasons(step).includes(selected) ? selected : EXTERNAL_INTERRUPTION;
}

const text = (value: unknown): string => value === null || value === undefined ? "—" : String(value);
const countdown = (start: number | null, duration: number): string => start === null ? "—" : `${(Math.max(0, start + duration - performance.now()) / 1000).toFixed(1)} s`;

export function runM0E5Runner(host: HTMLElement): () => void {
  const root = document.createElement("section"); root.setAttribute("aria-label", "M0E5 physical recollection runner");
  const title = document.createElement("h1"); title.textContent = "M0E5 calibration and neutral recollection";
  const status = document.createElement("p"); const details = document.createElement("pre"); details.style.whiteSpace = "pre-wrap";
  const controls = document.createElement("div"); const start = document.createElement("button"); start.textContent = "Initialize camera"; const ready = document.createElement("button"); ready.textContent = "Ready"; ready.disabled = true; const cancel = document.createElement("button"); cancel.textContent = "Cancel and retain evidence"; cancel.disabled = true; const reasonLabel = document.createElement("label"); reasonLabel.textContent = "Invalidation reason:"; const reason = document.createElement("select"); reason.id = "m0e5-invalidation-reason"; reasonLabel.htmlFor = reason.id; const invalidate = document.createElement("button"); invalidate.textContent = "Invalidate attempt"; invalidate.disabled = true; const replacement = document.createElement("button"); replacement.textContent = "Begin replacement"; replacement.disabled = true; controls.append(start, ready, cancel, reasonLabel, reason, invalidate, replacement); root.append(title, status, controls, details); host.replaceChildren(root);
  const source = new MediaPipeTrackingSource(); const writer = { write: (files: readonly { relativePath: string; contents: string }[]) => invoke<string>("write_m0e5_recollection_bundle", { files }) }; const runner = new M0E5EvidenceRunner({ source, writer, runId: `m0e5-${new Date().toISOString().replace(/[-:.TZ]/g, "")}` }); let disposed = false; let finalized = false; let output: string | null = null; let selectedReason: M0E5InvalidationReason = EXTERNAL_INTERRUPTION;
  const reasonLabels: Readonly<Record<M0E5InvalidationReason, string>> = { "external-interruption": "External interruption", "operator-moved-after-settling-during-stationary-capture": "Operator moved during stationary capture" };
  const render = (): void => { const state = runner.getState(); const step = state.steps[state.stepIndex]; selectedReason = normalizeM0E5InvalidationReason(step, selectedReason); const options = allowedM0E5InvalidationReasons(step); reason.replaceChildren(...options.map((value) => { const option = document.createElement("option"); option.value = value; option.textContent = reasonLabels[value]; return option; })); reason.value = selectedReason; reason.disabled = options.length === 1; status.textContent = `Status: ${state.status}${state.proceduralError ? ` — ${state.proceduralError}` : ""}`; start.disabled = !(state.status === "idle" || state.status === "ready"); start.textContent = state.status === "ready" ? "Begin recollection" : "Initialize camera"; ready.disabled = !(state.status === "running" && step?.kind === "transition"); cancel.disabled = !["initializing", "ready", "running", "invalidated"].includes(state.status); invalidate.disabled = state.status !== "running"; replacement.disabled = state.status !== "invalidated"; details.textContent = [`Scenario: ${text(step?.scenarioId)}`, `Cycle/trial: ${text(step?.cycleNumber ?? step?.trialNumber)}`, `Target: ${text(step?.targetMm)} mm (${text(step?.targetAxis)})`, `Physical instruction: ${text(step?.instruction)}`, `Phase: ${step?.kind === "transition" ? "Confirm target before hold" : text(step?.kind)}`, `Countdown: ${step?.durationMs === null || step?.durationMs === undefined ? "—" : countdown(state.stepStartedAtMs, step.durationMs)}`, "Camera requested: 640×360 @ 24 FPS; CPU; VIDEO; faces=1; facial matrix=true", `Camera actual: ${text(source.getCameraConfiguration().widthPx)}×${text(source.getCameraConfiguration().heightPx)} @ ${text(source.getCameraConfiguration().frameRate)} FPS`, `Selected estimator: mediapipe-facial-transform-v1 / v1 / fnv1a64-825a99daebb20f6c`, `MediaPipe package: ${MEDIAPIPE_PACKAGE_VERSION}`, `Attempt: ${state.attemptNumber}`, `Procedural invalidations: ${state.proceduralInvalidations.length}`, `Output path: ${output ?? "pending"}`].join("\n"); };
  const interval = window.setInterval(() => { if (disposed) return; const state = runner.tick(); if (state.status === "complete" && !finalized) { finalized = true; void runner.finalize().then((result) => { output = result.outputRoot; render(); }); } render(); }, 100);
  start.addEventListener("click", () => { void (runner.getState().status === "ready" ? Promise.resolve(runner.beginProcedure()) : runner.start()).then(render).catch((error: unknown) => { status.textContent = `Failed: ${String(error)}`; }); }); ready.addEventListener("click", () => { runner.confirmTargetReached(); render(); }); cancel.addEventListener("click", () => { finalized = true; void runner.cancel().then((result) => { output = result.outputRoot; render(); }); }); reason.addEventListener("change", () => { const step = runner.getState().steps[runner.getState().stepIndex]; selectedReason = normalizeM0E5InvalidationReason(step, reason.value as M0E5InvalidationReason); render(); }); invalidate.addEventListener("click", () => { const step = runner.getState().steps[runner.getState().stepIndex]; selectedReason = normalizeM0E5InvalidationReason(step, selectedReason); runner.invalidateCurrentAttempt(selectedReason, "Operator declared the current attempt procedurally invalid."); render(); }); replacement.addEventListener("click", () => { runner.beginReplacementAttempt(); render(); }); render();
  return () => { disposed = true; window.clearInterval(interval); if (!finalized) void source.stop(); root.remove(); };
}
