import { invoke } from "@tauri-apps/api/core";
import { MEDIAPIPE_PACKAGE_VERSION } from "../../mediapipe/mediapipeProvenance";
import { MediaPipeTrackingSource } from "../../mediapipe/mediapipeTrackingSource";
import { M0E5EvidenceRunner } from "./m0e5EvidenceRunner";

const text = (value: unknown): string => value === null || value === undefined ? "—" : String(value);
const countdown = (start: number | null, duration: number): string => start === null ? "—" : `${(Math.max(0, start + duration - performance.now()) / 1000).toFixed(1)} s`;

export function runM0E5Runner(host: HTMLElement): () => void {
  const root = document.createElement("section"); root.setAttribute("aria-label", "M0E5 physical recollection runner");
  const title = document.createElement("h1"); title.textContent = "M0E5 calibration and neutral recollection";
  const status = document.createElement("p"); const details = document.createElement("pre"); details.style.whiteSpace = "pre-wrap";
  const controls = document.createElement("div"); const start = document.createElement("button"); start.textContent = "Initialize camera"; const ready = document.createElement("button"); ready.textContent = "Ready"; ready.disabled = true; const cancel = document.createElement("button"); cancel.textContent = "Cancel and retain evidence"; cancel.disabled = true; const invalidate = document.createElement("button"); invalidate.textContent = "Invalidate attempt"; invalidate.disabled = true; const replacement = document.createElement("button"); replacement.textContent = "Begin replacement"; replacement.disabled = true; controls.append(start, ready, cancel, invalidate, replacement); root.append(title, status, controls, details); host.replaceChildren(root);
  const source = new MediaPipeTrackingSource(); const writer = { write: (files: readonly { relativePath: string; contents: string }[]) => invoke<string>("write_m0e5_recollection_bundle", { files }) }; const runner = new M0E5EvidenceRunner({ source, writer, runId: `m0e5-${new Date().toISOString().replace(/[-:.TZ]/g, "")}` }); let disposed = false; let finalized = false; let output: string | null = null;
  const render = (): void => { const state = runner.getState(); const step = state.steps[state.stepIndex]; status.textContent = `Status: ${state.status}${state.proceduralError ? ` — ${state.proceduralError}` : ""}`; start.disabled = !(state.status === "idle" || state.status === "ready"); start.textContent = state.status === "ready" ? "Begin recollection" : "Initialize camera"; ready.disabled = !(state.status === "running" && step?.kind === "transition"); cancel.disabled = !["initializing", "ready", "running", "invalidated"].includes(state.status); invalidate.disabled = state.status !== "running"; replacement.disabled = state.status !== "invalidated"; details.textContent = [`Scenario: ${text(step?.scenarioId)}`, `Cycle/trial: ${text(step?.cycleNumber ?? step?.trialNumber)}`, `Target: ${text(step?.targetMm)} mm (${text(step?.targetAxis)})`, `Physical instruction: ${text(step?.instruction)}`, `Phase: ${step?.kind === "transition" ? "Confirm target before hold" : text(step?.kind)}`, `Countdown: ${step?.durationMs === null || step?.durationMs === undefined ? "—" : countdown(state.stepStartedAtMs, step.durationMs)}`, "Camera requested: 640×360 @ 24 FPS; CPU; VIDEO; faces=1; facial matrix=true", `Camera actual: ${text(source.getCameraConfiguration().widthPx)}×${text(source.getCameraConfiguration().heightPx)} @ ${text(source.getCameraConfiguration().frameRate)} FPS`, `Selected estimator: mediapipe-facial-transform-v1 / v1 / fnv1a64-825a99daebb20f6c`, `MediaPipe package: ${MEDIAPIPE_PACKAGE_VERSION}`, `Attempt: ${state.attemptNumber}`, `Procedural invalidations: ${state.proceduralInvalidations.length}`, `Output path: ${output ?? "pending"}`].join("\n"); };
  const interval = window.setInterval(() => { if (disposed) return; const state = runner.tick(); if (state.status === "complete" && !finalized) { finalized = true; void runner.finalize().then((result) => { output = result.outputRoot; render(); }); } render(); }, 100);
  start.addEventListener("click", () => { void (runner.getState().status === "ready" ? Promise.resolve(runner.beginProcedure()) : runner.start()).then(render).catch((error: unknown) => { status.textContent = `Failed: ${String(error)}`; }); }); ready.addEventListener("click", () => { runner.confirmTargetReached(); render(); }); cancel.addEventListener("click", () => { finalized = true; void runner.cancel().then((result) => { output = result.outputRoot; render(); }); }); invalidate.addEventListener("click", () => { runner.invalidateCurrentAttempt(stepReason(runner), "Operator declared the current attempt procedurally invalid."); render(); }); replacement.addEventListener("click", () => { runner.beginReplacementAttempt(); render(); }); render();
  return () => { disposed = true; window.clearInterval(interval); if (!finalized) void source.stop(); root.remove(); };
}
function stepReason(runner: M0E5EvidenceRunner): "external-interruption" | "operator-moved-after-settling-during-stationary-capture" { return runner.getState().steps[runner.getState().stepIndex]?.scenarioId === "neutral-stationary" ? "operator-moved-after-settling-during-stationary-capture" : "external-interruption"; }
